DROP TABLE IF EXISTS Auditoria CASCADE;

DROP TABLE IF EXISTS Avion CASCADE;

DROP TABLE IF EXISTS Barco CASCADE;

DROP TABLE IF EXISTS Metodo_de_Pago CASCADE;

DROP TABLE IF EXISTS Compania_Crucero CASCADE;

DROP TABLE IF EXISTS Operador_Turistico CASCADE;

DROP TABLE IF EXISTS Aerolinea CASCADE;

DROP TABLE IF EXISTS Compania_Transporte_Terrestre CASCADE;

DROP TABLE IF EXISTS Hotel CASCADE;

DROP TABLE IF EXISTS Cli_MP CASCADE;

DROP TABLE IF EXISTS Cliente CASCADE;

DROP TABLE IF EXISTS Comida CASCADE;

DROP TABLE IF EXISTS Crucero CASCADE;

DROP TABLE IF EXISTS Cuota CASCADE;

DROP TABLE IF EXISTS Doc_Pas CASCADE;

DROP TABLE IF EXISTS Documento CASCADE;

DROP TABLE IF EXISTS Empleado CASCADE;

DROP TABLE IF EXISTS Estatus CASCADE;

DROP TABLE IF EXISTS Financiamiento CASCADE;

DROP TABLE IF EXISTS Hospedaje CASCADE;

DROP TABLE IF EXISTS Itinerario CASCADE;

DROP TABLE IF EXISTS Lugar CASCADE;

DROP TABLE IF EXISTS Pago CASCADE;

DROP TABLE IF EXISTS Pago_Reembolsado CASCADE;

DROP TABLE IF EXISTS Paquete_Turistico CASCADE;

DROP TABLE IF EXISTS Pasajero CASCADE;

DROP TABLE IF EXISTS Preferencia CASCADE;

DROP TABLE IF EXISTS Pri_Rol CASCADE;

DROP TABLE IF EXISTS Privilegio CASCADE;

DROP TABLE IF EXISTS Promocion CASCADE;

DROP TABLE IF EXISTS Reclamo CASCADE;

DROP TABLE IF EXISTS Reembolso CASCADE;

DROP TABLE IF EXISTS Registro_Reclamos CASCADE;

DROP TABLE IF EXISTS Resenas CASCADE;

DROP TABLE IF EXISTS Reserva CASCADE;

DROP TABLE IF EXISTS Restaurante CASCADE;

DROP TABLE IF EXISTS Restriccion_Paquete CASCADE;

DROP TABLE IF EXISTS Rol CASCADE;

DROP TABLE IF EXISTS Ruta CASCADE;

DROP TABLE IF EXISTS Servicio_Adicional CASCADE;

DROP TABLE IF EXISTS Tasa_de_Cambio CASCADE;

DROP TABLE IF EXISTS Terminal CASCADE;

DROP TABLE IF EXISTS Tipo_Documento CASCADE;

DROP TABLE IF EXISTS Transporte_Terrestre CASCADE;

DROP TABLE IF EXISTS Usuario CASCADE;

DROP TABLE IF EXISTS Vehiculo CASCADE;

DROP TABLE IF EXISTS Vuelo CASCADE;

DROP TABLE IF EXISTS Wishlist CASCADE;